import type { ColorTheme } from '@/types/theme'

export const COLOR_THEMES: ColorTheme[] = [
  {
    id: 'minimal-white',
    name: '极简白',
    aesthetic: '极简',
    colors: {
      background: '#FFFFFF',
      surface: '#F8F8F8',
      primary: '#1A1A1A',
      secondary: '#555555',
      accent: '#000000',
      text: '#1A1A1A',
      textMuted: '#888888',
    },
  },
  {
    id: 'dark-academia',
    name: '暗色学院',
    aesthetic: '学院风',
    colors: {
      background: '#1C1914',
      surface: '#2A2520',
      primary: '#D4B896',
      secondary: '#9A8468',
      accent: '#E8C99A',
      text: '#EDE0CC',
      textMuted: '#9A8468',
    },
    gradientPresets: [
      ['#1C1914', '#2A2520'],
      ['#2A2520', '#1C1914'],
    ],
  },
  {
    id: 'soft-pink',
    name: '樱花粉',
    aesthetic: '日系甜蜜',
    colors: {
      background: '#FFF0F3',
      surface: '#FFE4EA',
      primary: '#C9184A',
      secondary: '#FF4D6D',
      accent: '#FF758F',
      text: '#590D22',
      textMuted: '#C9184A',
    },
  },
  {
    id: 'risograph',
    name: 'Risograph',
    aesthetic: '印刷风',
    colors: {
      background: '#F5F0E8',
      surface: '#EDE8D8',
      primary: '#E8572A',
      secondary: '#3D6B8C',
      accent: '#F5A623',
      text: '#1A1A2E',
      textMuted: '#6B6B6B',
    },
    gradientPresets: [
      ['#E8572A', '#F5A623'],
      ['#3D6B8C', '#E8572A'],
    ],
  },
  {
    id: 'cottagecore',
    name: '乡村风',
    aesthetic: '田园诗意',
    colors: {
      background: '#F7F3ED',
      surface: '#EDE6D8',
      primary: '#7B6F4A',
      secondary: '#A89875',
      accent: '#5C7A45',
      text: '#3D3426',
      textMuted: '#8B7D5E',
    },
  },
  {
    id: 'midnight',
    name: '午夜蓝',
    aesthetic: '深邃宁静',
    colors: {
      background: '#0A0E1A',
      surface: '#141929',
      primary: '#7B9FE0',
      secondary: '#4A6FA5',
      accent: '#A8C5F0',
      text: '#E8EDF8',
      textMuted: '#6B7A9A',
    },
    gradientPresets: [
      ['#0A0E1A', '#1A2340'],
      ['#0D1B3E', '#0A0E1A'],
    ],
  },
  {
    id: 'matcha',
    name: '抹茶',
    aesthetic: '和风清新',
    colors: {
      background: '#F0F4EF',
      surface: '#E2EAE0',
      primary: '#4A7C59',
      secondary: '#7FAD8B',
      accent: '#2D5E3C',
      text: '#1E3A2B',
      textMuted: '#6A9075',
    },
  },
  {
    id: 'retro-sunset',
    name: '复古日落',
    aesthetic: '70年代复古',
    colors: {
      background: '#F5E6D3',
      surface: '#EDD9BC',
      primary: '#D4520A',
      secondary: '#E8842C',
      accent: '#B8380A',
      text: '#2C1A0A',
      textMuted: '#8A5A3A',
    },
    gradientPresets: [
      ['#D4520A', '#F0A030'],
      ['#E8842C', '#D4520A'],
    ],
  },
  {
    id: 'lavender-dream',
    name: '薰衣草',
    aesthetic: '梦幻紫调',
    colors: {
      background: '#F5F0FF',
      surface: '#EBE0FF',
      primary: '#7B5EA7',
      secondary: '#9B7EC8',
      accent: '#5A3D8A',
      text: '#2A1A4A',
      textMuted: '#8B70B0',
    },
  },
  {
    id: 'monochrome',
    name: '黑白摄影',
    aesthetic: '极致黑白',
    colors: {
      background: '#F2F2F2',
      surface: '#E5E5E5',
      primary: '#1A1A1A',
      secondary: '#4A4A4A',
      accent: '#000000',
      text: '#111111',
      textMuted: '#777777',
    },
  },
  {
    id: 'y2k-neon',
    name: 'Y2K 荧光',
    aesthetic: '赛博朋克',
    colors: {
      background: '#0D0D1A',
      surface: '#1A1A2E',
      primary: '#FF00FF',
      secondary: '#00FFFF',
      accent: '#FFFF00',
      text: '#FFFFFF',
      textMuted: '#9999CC',
    },
    gradientPresets: [
      ['#FF00FF', '#00FFFF'],
      ['#0D0D1A', '#1A0D2E'],
    ],
  },
  {
    id: 'coffee',
    name: '咖啡馆',
    aesthetic: '温暖棕调',
    colors: {
      background: '#F4ECD8',
      surface: '#E8D8B8',
      primary: '#5C3D1E',
      secondary: '#8B6340',
      accent: '#3D2510',
      text: '#2C1A08',
      textMuted: '#8B6B4A',
    },
  },
  {
    id: 'ocean',
    name: '深海',
    aesthetic: '海洋蓝绿',
    colors: {
      background: '#E8F4F8',
      surface: '#D0E8F0',
      primary: '#006B8F',
      secondary: '#0094B5',
      accent: '#004D6B',
      text: '#00293D',
      textMuted: '#5A8FA0',
    },
  },
  {
    id: 'clay',
    name: '陶土',
    aesthetic: '大地色系',
    colors: {
      background: '#F0EAE0',
      surface: '#E5D9C8',
      primary: '#A0552A',
      secondary: '#C47848',
      accent: '#7A3C1C',
      text: '#3D1F0C',
      textMuted: '#9A7055',
    },
  },
  {
    id: 'spring',
    name: '春日',
    aesthetic: '清新明亮',
    colors: {
      background: '#FAFFF5',
      surface: '#F0FFE8',
      primary: '#3D8B37',
      secondary: '#5FAD58',
      accent: '#2A6E24',
      text: '#1A3518',
      textMuted: '#5A8A54',
    },
  },
]

export function getThemeById(id: string): ColorTheme {
  return COLOR_THEMES.find((t) => t.id === id) ?? COLOR_THEMES[0]
}
